controllers:
  NotFound:
    controller: Handy\Controller\NotFoundController
    method: index


supported_content_types: ["application/json"]

global_path_prefix: ""

security_provider: Handy\Security\EmptySecurityProvider